# Generated by Django 3.1.3 on 2020-11-16 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Assest Description')),
                ('serialNumber', models.CharField(max_length=200, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code', models.CharField(max_length=200, null=True, verbose_name='Tag Number')),
                ('category', models.CharField(choices=[('Computer Laptop', 'Computer Laptop'), ('Computer Desktop', 'Computer Desktop'), ('4G Router', '4G Router'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Television', 'Television'), ('Decoder', 'Decoder')], max_length=200, null=True)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Given', 'Given')], default='Available', max_length=20, verbose_name='Device Status')),
                ('userRecord', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Undermaintenance', 'Undermaintenance'), ('Retirement', 'Retirement')], default='work', max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('address', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.address')),
                ('device', models.OneToOneField(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='registerItem.stock')),
            ],
        ),
    ]
